import React, { useEffect } from "react";
import { Box, Typography } from "@mui/material";
import Loading from "../../../Components/Loading/Loading";
import BookCard from "./BookCard";
import FlexBetween from "../../../Components/FlexBetween";
import { InfoOutlined } from "@mui/icons-material";

const DisplayBooks = ({ booksData, loading }) => {
  useEffect(() => {}, [loading]);

  return (
    <FlexBetween
      flexDirection={"column"}
      flexWrap={"wrap"}
      padding={"0.5rem"}
      width={"100%"}
      gap={1}
    >
      {loading && !booksData ? (
        <Loading />
      ) : booksData ? (
        <>
          <Typography variant="h6" color={"secondary"}>
            <InfoOutlined /> Click on book card to check total rent generated by
            it, issue book to some user and also it shows the past issuer list
            and current holder
          </Typography>
          {booksData.map((book) => (
            <BookCard key={book._id} book={book} />
          ))}
        </>
      ) : (
        <Box>No books found as per applied filter</Box>
      )}
    </FlexBetween>
  );
};

export default DisplayBooks;
